// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MacrosService provides file-system operations scoped to the Macros/ directory.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAppVersion returns the current app version info.
 */
export function GetAppVersion(): $CancellablePromise<$models.AppVersionInfo | null> {
    return $Call.ByID(1096061933);
}

/**
 * GetReleaseCommand returns the shell command to create a GitHub Release.
 */
export function GetReleaseCommand(): $CancellablePromise<string> {
    return $Call.ByID(2002886338);
}

/**
 * GetRootPath returns the absolute path of the Macros directory.
 */
export function GetRootPath(): $CancellablePromise<string> {
    return $Call.ByID(2999625463);
}

/**
 * GetVersionContent returns the content of a specific version.
 */
export function GetVersionContent(subpath: string, versionID: string): $CancellablePromise<string> {
    return $Call.ByID(3778834545, subpath, versionID);
}

/**
 * GetVersionHistory returns all recorded versions.
 */
export function GetVersionHistory(): $CancellablePromise<$models.VersionEntry[] | null> {
    return $Call.ByID(108604676);
}

/**
 * GetVersions lists all saved versions for a file, newest first.
 */
export function GetVersions(subpath: string): $CancellablePromise<$models.VersionInfo[] | null> {
    return $Call.ByID(424314389, subpath);
}

/**
 * ListDir returns entries inside the given subpath (or root if empty).
 */
export function ListDir(subpath: string): $CancellablePromise<$models.FileEntry[] | null> {
    return $Call.ByID(871135051, subpath);
}

/**
 * PublishVersion bumps the version and records a changelog entry.
 * bumpType: "major", "minor", "patch".
 */
export function PublishVersion(changelog: string, bumpType: string): $CancellablePromise<$models.AppVersionInfo | null> {
    return $Call.ByID(3334719057, changelog, bumpType);
}

/**
 * ReadFile returns the contents of the file at the given subpath.
 */
export function ReadFile(subpath: string): $CancellablePromise<string> {
    return $Call.ByID(2073730070, subpath);
}

/**
 * RestoreVersion replaces the current file with the given version and creates a
 * backup of the current content first.
 */
export function RestoreVersion(subpath: string, versionID: string): $CancellablePromise<void> {
    return $Call.ByID(2953742810, subpath, versionID);
}

/**
 * SaveFile writes content to the file, creates a version backup, and updates
 * metadata.json (SHA1 / Size / ModifiedDate) when the file is tracked there.
 */
export function SaveFile(subpath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(2556808975, subpath, content);
}
