// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppVersionInfo holds the current app version and release date.
 */
export interface AppVersionInfo {
    "version": string;
    "date": string;
}

/**
 * FileEntry represents a file or directory in the Macros tree.
 */
export interface FileEntry {
    "name": string;
    "isDir": boolean;
    "path": string;
}

/**
 * VersionEntry is one entry in the version history.
 */
export interface VersionEntry {
    "version": string;
    "date": string;
    "changelog": string;
}

/**
 * VersionInfo describes a single saved version.
 */
export interface VersionInfo {
    "versionId": string;
    "modifiedAt": string;
    "size": number;
    "sha1": string;
}
